# Используйте официальный образ Python как базовый
FROM python:3.9

# Установите рабочий каталог в контейнере
WORKDIR /usr/src/app

# Копируйте файлы зависимостей и устанавливайте их
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируйте исходный код вашего приложения в контейнер
COPY . .

# Запускайте приложение при старте контейнера
CMD ["python", "./main.py"]
